#!/bin/bash
cp ~/alx-low_level_programming/0x07-pointers_arrays_strings/*.c ~/alx-low_level_programming/0x09-static_libraries
cp ~/alx-low_level_programming/0x06-pointers_arrays_strings/*.c ~/alx-low_level_programming/0x09-static_libraries
